# Generated by Django 6.0.3 on 2026-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_posted_at_job_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('reviewed', 'reviewed'), ('interview', 'interview'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('intern', 'intern'), ('part-time', 'part-time'), ('full-time', 'full-time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('employer', 'employer'), ('admin', 'admin')], default='student', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(help_text='Resume Name', max_length=200),
        ),
    ]
