# Generated by Django 6.0.3 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(
                choices=[
                    ('accounting', 'Accounting'),
                    ('agriculture', 'Agriculture, fishing & forestry'),
                    ('architecture', 'Architecture'),
                    ('automotive', 'Automotive'),
                    ('banking_finance_insurance', 'Banking, finance & insurance'),
                    ('construction_roading', 'Construction & roading'),
                    ('customer_service', 'Customer service'),
                    ('education', 'Education'),
                    ('engineering', 'Engineering'),
                    ('executive_management', 'Executive & general management'),
                    ('government_council', 'Government & council'),
                    ('healthcare', 'Healthcare'),
                    ('hospitality', 'Hospitality & tourism'),
                    ('information_technology', 'Information technology'),
                    ('marketing', 'Marketing'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=50,
                verbose_name='Category',
            ),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='jobs_job_category_idx'),
        ),
    ]
