# Generated by Django 6.0.3 on 2026-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('middle_school', 'Middle School'), ('high_school', 'High School'), ('vocational_high_school', 'Vocational High School'), ('junior_college', 'Junior College'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate'), ('other', 'Other')], max_length=30, verbose_name='Education Level'),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_unit',
            field=models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='years', max_length=10, verbose_name='Experience Unit'),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Work Experience'),
        ),
    ]
